"""
Services layer for business logic orchestration.

Provides reusable services that can be consumed by CLI, Streamlit, FastAPI, etc.
"""

from services.asset_service import (
    AssetCreationResult,
    create_asset_with_data,
    print_asset_creation_result,
)
from services.position_service import (
    TradeResult,
    buy_position,
    sell_position,
    print_trade_result,
)
from services.market_index_service import (
    IndexSummary,
    IndexPricePoint,
    IndexPriceHistory,
    SyncResult,
    get_all_indices,
    get_index_by_symbol,
    get_index_by_id,
    get_indices_by_category,
    get_equity_indices,
    get_index_prices,
    get_latest_index_prices,
    get_index_returns,
    create_index,
    get_or_create_index,
    sync_index_prices,
    add_index_prices,
    get_configured_indices,
    ensure_indices_seeded,
)
from services.tag_service import (
    TagResult,
    TagWithCount,
    TagListResult,
    AssetTagsResult,
    create_tag,
    get_tag_by_id,
    get_tag_by_name,
    get_all_tags,
    get_all_tags_with_counts,
    rename_tag,
    delete_tag,
    get_tags_for_asset,
    get_tags_for_ticker,
    attach_tag_to_asset,
    detach_tag_from_asset,
    set_asset_tags,
    set_asset_tags_by_names,
    get_assets_by_tags,
    get_assets_by_tag_names,
    get_untagged_assets,
    get_assets_for_tag,
)

__all__ = [
    # Asset service
    "AssetCreationResult",
    "create_asset_with_data",
    "print_asset_creation_result",
    # Position service
    "TradeResult",
    "buy_position",
    "sell_position",
    "print_trade_result",
    # Market index service
    "IndexSummary",
    "IndexPricePoint",
    "IndexPriceHistory",
    "SyncResult",
    "get_all_indices",
    "get_index_by_symbol",
    "get_index_by_id",
    "get_indices_by_category",
    "get_equity_indices",
    "get_index_prices",
    "get_latest_index_prices",
    "get_index_returns",
    "create_index",
    "get_or_create_index",
    "sync_index_prices",
    "add_index_prices",
    "get_configured_indices",
    "ensure_indices_seeded",
    # Tag service
    "TagResult",
    "TagWithCount",
    "TagListResult",
    "AssetTagsResult",
    "create_tag",
    "get_tag_by_id",
    "get_tag_by_name",
    "get_all_tags",
    "get_all_tags_with_counts",
    "rename_tag",
    "delete_tag",
    "get_tags_for_asset",
    "get_tags_for_ticker",
    "attach_tag_to_asset",
    "detach_tag_from_asset",
    "set_asset_tags",
    "set_asset_tags_by_names",
    "get_assets_by_tags",
    "get_assets_by_tag_names",
    "get_untagged_assets",
    "get_assets_for_tag",
]
